backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: public/images/cms
public_folder: /images/cms
collections:
  - name: "events"
    label: "Events"
    files:
      - label: "Events Page"
        name: "events"
        file: "src/pages/events.json"
        fields:
          - label: "Events list"
            name: "events"
            widget: list
            fields:
            - {label: Title, name: title, widget: string}
            - {label: Address, name: address, widget: string }
            # * in future, use widget: markdown
            - {label: Description, name: description, widget: string }
            - label: "Date"
              name: "Date"
              widget: "datetime"
              format: "LLL"
              date_format: true
              time_format: true
